spring:
  application:
    name: scheduler

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health, prometheus
      base_path:
      path_mapping:
        prometheus: metrics
  endpoint:
    health:
      show-details: 'ALWAYS'
  health:
    elasticsearch:
      enabled: false
  prometheus:
    security:
      login: metrics0@advcash.com
      password: PalP#$%0009
